### ISSUE TITLE
Extracting 0 file

### ISSUE THREAD

**Issue by RichardPaulAstley** [drgoku282/MassPKXextractor#1]
Hi,

First thanks for this tool once again (i'll never say that enough)

I've tried the first version, but when i choose my folder with some saves, i'm just getting a "0 Saves files processed correctly"

So i've two cases : 

- Using many saves : All gens, but .dsv + .sav. Some of the saves are just new (saved in front of the starter for RNGing stuff), some are from hack-rom. IF one is wrong, it just cancels everything

- Using Gen 3 Finished Saves : Working fine.

So, no problem with Gen 3 games, but an "ignore" save + support .dsv would be amazing

Thanks !

**Comment by drgoku282** [comment]
The program uses PKHeX.Core, so it will only recognize save files that you can open in PKHeX, so that's why the rom hack was probably not recognized.

Can you attach a .dsv file in projectpokemon to test it?

**Comment by RichardPaulAstley** [comment]
Hey ! 

Sorry I've updated the issue in order to be more clear. 
I don't want to have this kind of saves extracted (i want to keep CLEAR saves only so no problem) but the script stops rather than ignoring it completly.

And gonna send this on Project Pokemon (editing the first post i made there)

Edit : save uploaded

Thanks !

**Comment by drgoku282** [comment]
Try with version 1.1, now the program should ignore saves that it can read and show them at the end.

**Comment by RichardPaulAstley** [comment]
Just tried it with 20/30 saves, got it to work.

So you can close this one without any problem.
It's 5AM, i'm going to sleep a little.

I'm gonna check with A LOT of saves to see any problem tomorrow. But tried with every type of file, no problem.

Edit : just found a LITTLE LITTLE bug.
It doesn't keep in memory the "output" folder path. But no problem for the input.

Thank you !
